apiVersion: apps/v1
kind: Deployment
metadata:
  name: ts-api
spec:
  replicas: 4
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: ts-api
  template:
    metadata:
      labels:
        app: ts-api
    spec:
      containers:
        - name: ts-api
          image: ts-api:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          env:
            - name: REDIS_HOST
              value: "redis.default"
            - name: REDIS_PORT
              value: "6379"
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
